name: workout_timer
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  audioplayers: ^6.5.0
  circular_countdown_timer: ^0.2.4
  flutter:
    sdk: flutter

  numberpicker: ^2.1.2
  path_provider: ^2.1.5
  wakelock_plus: ^1.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/ding.mp3
    - assets/gong.mp3
    - assets/beep.mp3
